orders-service:
  image:
    repository: 490059499947.dkr.ecr.us-east-1.amazonaws.com/dev-orders-service
    tag: c1e2ba45e42e3e628bdb0cc894493b549cf38a7f
products-service:
  image:
    repository: 490059499947.dkr.ecr.us-east-1.amazonaws.com/dev-products-service
    tag: 847eb78f0182999360565c4f5c312340603df109
users-service:
  image:
    repository: 490059499947.dkr.ecr.us-east-1.amazonaws.com/dev-users-service
    tag: 04fbf96ed9abf4b0ebceb89aa4cc67c39ab3f015
