orders-service:
  image:
    repository: 490059499947.dkr.ecr.us-east-1.amazonaws.com/dev-orders-service
    tag: c8b400d7babff6420de3534991302e16a28e230b
products-service:
  image:
    repository: 490059499947.dkr.ecr.us-east-1.amazonaws.com/dev-products-service
    tag: 5c33af109b178dbdd12c3c970caadaaee3580c48
users-service:
  image:
    repository: 490059499947.dkr.ecr.us-east-1.amazonaws.com/dev-users-service
    tag: 70a2226b443201c988e35c4c26ba5d1394257f1a
