apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: users-service
  namespace: dev
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: users-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s